# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  api-tests:
    docker:
      - image: mcr.microsoft.com/playwright:v1.27.0-focal
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - run: npm install
      - run:
          name: "api-tests"
          command: PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml npx playwright test api-tests.spec.ts --reporter=junit --project=chromium
      - store_test_results:
          path: results.xml
workflows:
  api-tests-workflow:
    jobs:
      - api-tests
